### ISSUE TITLE
프론트엔드 기술 관련 제안

### ISSUE THREAD

**Issue by Seogeurim** [telbby/telbby-frontend#5]
프론트엔드 기술 관련 두 가지 제안을 해볼까 합니다. 최근에 리액트 고급 안내서 스터디를 하면서 프로젝트에 도입해보면 좋겠다고 생각했던 내용들입니다.

## 1. Code-Splitting 도입

> 영문 : https://reactjs.org/docs/code-splitting.html#route-based-code-splitting
> 한글 : https://ko.reactjs.org/docs/code-splitting.html#route-based-code-splitting

코드 분할에 대해 아직 막연하게 이론적으로만 이해하고 있는 상태입니다. 공식 문서를 확인했을 때 도입하기 가장 좋은 곳이 라우트라고 합니다. 웹팩 설정과 더불어 한 번 적용해보는 것은 어떤가요?

## 2. Error Boundary 생성

> 영문 : https://reactjs.org/docs/error-boundaries.html
> 한글 : https://ko.reactjs.org/docs/error-boundaries.html

프론트엔드 에러 핸들링을 Error Boundary를 도입하여 적절히 처리할 수 있다고 합니다. 라이프사이클을 이용해 처리하는 방식입니다. 프로젝트 초기부터 범용적인 Error Boundary를 하나 만들어놓고 시작하는 것도 좋다는 생각입니다. 어떤가요?

**Comment by hseoy** [comment]
1. Code Splitting의 경우에는 추후에 개발이 어느 정도 진행된 후에 도입해보면 어떨까 싶습니다. Code Splitting이 번들의 크기를 줄여 초기 로딩 속도를 줄이기 위한 것인데 이론적으로만 이해하고 계신 상태면 도입 전과 도입 후의 로딩 속도를 측정해서 그 효과를 체감해보는 것도 좋을 것 같다는 생각이 듭니다. 살펴보니까 도입에 오랜 시간이 걸리지 않다고 보여져서 추후에 도입해도 문제가 없을 것이라 생각합니다. 

2. 좋은 제안인 것 같습니다. 동의합니다.

**Comment by jonghopark95** [comment]
저도 윤서님과 동일한 의견입니다.

1. 처음부터 Code Splitting을 도입해서 진행하면 체감도 크게 느껴지지 않고, 하나의 빌드파일만 있는 것보다 느릴 수도 있다고 생각합니다 윤서님말대로 개발이 어느정도 진행되고, 도입 전 후 로드 속도를 비교해 보는 것도 좋다고 생각합니다!!

2. Error Boundary 는 정말 좋은 의견같아요 테스트 코드도 작성해보며 많은 것을 배울 수 있다고 생각합니다 :)

**Comment by Seogeurim** [comment]
1. 오 좋은 생각이네요 !! 추후 버전1 개발이 완료된 후 도입 전후를 비교해보면 좋을 것 같습니다 !!
2. Error Boundary 는 그럼 좀 더 찾아보고 한 번 이슈 파서 진행해보도록 하겠습니다 !
